### ISSUE TITLE
Прикрутить авторизация на бриз для админ панели

### ISSUE THREAD

**Issue by vasilysmolin** [DemetriSam/vvn-270822#1]
1) Надо определить будут ли роли и права в админской части? 
2) Будем ли защизать базовой атворизацие админку, для безопасности?

**Comment by DemetriSam** [comment]
2. Админку будем защищать, обязательно

**Comment by DemetriSam** [comment]
1. 
- На данном этапе разделять роли я не планирую. 
- Управление ролями и правами через админку точно не хочу сейчас делать. 
- Было бы здорово оставить возможность создать какую-то более ограниченную в правах роль в будущем руками.
